In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv('https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv')

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [9]:
df.describe()

SEVERITYCODE              X              Y       OBJECTID  \
count  194673.000000  189339.000000  189339.000000  194673.000000   
mean        1.298901    -122.330518      47.619543  108479.364930   
std         0.457778       0.029976       0.056157   62649.722558   
min         1.000000    -122.419091      47.495573       1.000000   
25%         1.000000    -122.348673      47.575956   54267.000000   
50%         1.000000    -122.330224      47.615369  106912.000000   
75%         2.000000    -122.311937      47.663664  162272.000000   
max         2.000000    -122.238949      47.734142  219547.000000   

              INCKEY      COLDETKEY         INTKEY  SEVERITYCODE.1  \
count  194673.000000  194673.000000   65070.000000   194673.000000   
mean   141091.456350  141298.811381   37558.450576        1.298901   
std     86634.402737   86986.542110   51745.990273        0.457778   
min      1001.000000    1001.000000   23807.000000        1.000000   
25%     70383.000000   70383.000000   28667.000000        1.000000   
50%    123363.000000  123363.000000   29973.000000        1.000000   
75%    203319.000000  203459.000000   33973.000000        2.000000   
max    331454.000000  332954.000000  757580.000000        2.000000   

         PERSONCOUNT       PEDCOUNT    PEDCYLCOUNT       VEHCOUNT  \
count  194673.000000  194673.000000  194673.000000  194673.000000   
mean        2.444427       0.037139       0.028391       1.920780   
std         1.345929       0.198150       0.167413       0.631047   
min         0.000000       0.000000       0.000000       0.000000   
25%         2.000000       0.000000       0.000000       2.000000   
50%         2.000000       0.000000       0.000000       2.000000   
75%         3.000000       0.000000       0.000000       2.000000   
max        81.000000       6.000000       2.000000      12.000000   

        SDOT_COLCODE    SDOTCOLNUM     SEGLANEKEY  CROSSWALKKEY  
count  194673.000000  1.149360e+05  194673.000000  1.946730e+05  
mean       13.867768  7.972521e+06     269.401114  9.782452e+03  
std         6.868755  2.553533e+06    3315.776055  7.226926e+04  
min         0.000000  1.007024e+06       0.000000  0.000000e+00  
25%        11.000000  6.040015e+06       0.000000  0.000000e+00  
50%        13.000000  8.023022e+06       0.000000  0.000000e+00  
75%        14.000000  1.015501e+07       0.000000  0.000000e+00  
max        69.000000  1.307202e+07  525241.000000  5.239700e+06

In [12]:
df['WEATHER'].value_counts()

Clear                       111135
Raining                      33145
Overcast                     27714
Unknown                      15091
Snowing                        907
Other                          832
Fog/Smog/Smoke                 569
Sleet/Hail/Freezing Rain       113
Blowing Sand/Dirt               56
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [13]:
df['ROADCOND'].value_counts()

Dry               124510
Wet                47474
Unknown            15078
Ice                 1209
Snow/Slush          1004
Other                132
Standing Water       115
Sand/Mud/Dirt         75
Oil                   64
Name: ROADCOND, dtype: int64

In [14]:
df['LIGHTCOND'].value_counts()

Daylight                    116137
Dark - Street Lights On      48507
Unknown                      13473
Dusk                          5902
Dawn                          2502
Dark - No Street Lights       1537
Dark - Street Lights Off      1199
Other                          235
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

In [15]:
df['JUNCTIONTYPE'].value_counts()

Mid-Block (not related to intersection)              89800
At Intersection (intersection related)               62810
Mid-Block (but intersection related)                 22790
Driveway Junction                                    10671
At Intersection (but not related to intersection)     2098
Ramp Junction                                          166
Unknown                                                  9
Name: JUNCTIONTYPE, dtype: int64

In [27]:
encoding_weather={'WEATHER':{'Overcast':1, 'Raining':2, 'Clear':3, 'Unknown':4, 'Other':4, 'Snowing':5,
       'Fog/Smog/Smoke':6, 'Sleet/Hail/Freezing Rain':7, 'Blowing Sand/Dirt':8,
       'Severe Crosswind':9, 'Partly Cloudy':10}}
df.replace(encoding_weather, inplace=True)
df['WEATHER'].value_counts()

3.0     111135
2.0      33145
1.0      27714
4.0      15923
5.0        907
6.0        569
7.0        113
8.0         56
9.0         25
10.0         5
Name: WEATHER, dtype: int64

In [31]:
encoding_roadcond={'ROADCOND':{'Wet':1, 'Dry':2, 'Unknown':3, 'Snow/Slush':4, 'Ice':5, 'Other':2,
       'Sand/Mud/Dirt':6, 'Standing Water':7, 'Oil':8}}
df.replace(encoding_roadcond, inplace=True)
df['ROADCOND'].value_counts()

2.0    124642
1.0     47474
3.0     15078
5.0      1209
4.0      1004
7.0       115
6.0        75
8.0        64
Name: ROADCOND, dtype: int64

In [33]:
encoding_lightcond={'LIGHTCOND':{'Daylight':1, 'Dark - Street Lights On':2, 'Dark - No Street Lights':2,
       'Unknown':2, 'Dusk':3, 'Dawn':4, 'Dark - Street Lights Off':2,
       'Other':1, 'Dark - Unknown Lighting':2}}
df.replace(encoding_lightcond, inplace=True)
df['LIGHTCOND'].value_counts()

1.0    116372
2.0     64727
3.0      5902
4.0      2502
Name: LIGHTCOND, dtype: int64

In [35]:
encoding_JUNCTIONTYPE={'JUNCTIONTYPE':{'At Intersection (intersection related)':1,
       'Mid-Block (not related to intersection)':2, 'Driveway Junction':3,
       'Mid-Block (but intersection related)':3,
       'At Intersection (but not related to intersection)':1,'Unknown':2, 'Ramp Junction':4}}
df.replace(encoding_JUNCTIONTYPE, inplace=True)
df['JUNCTIONTYPE'].value_counts()

2.0    89809
1.0    64908
3.0    33461
4.0      166
Name: JUNCTIONTYPE, dtype: int64

In [98]:
df.fillna(0,inplace=True)

In [104]:
features=['WEATHER', 'ROADCOND', 'LIGHTCOND','JUNCTIONTYPE','SPEEDING']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[features],df['SEVERITYCODE'],test_size=0.3)

In [105]:
from sklearn.ensemble import RandomForestClassifier
rdf = RandomForestClassifier(n_estimators=300,random_state=35)

rdf.fit(X_train,y_train)

y_pred=rdf.predict(X_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Accuracy: 0.7002671141399267
[[40712   249]
 [17256   185]]
              precision    recall  f1-score   support

           1       0.70      0.99      0.82     40961
           2       0.43      0.01      0.02     17441

   micro avg       0.70      0.70      0.70     58402
   macro avg       0.56      0.50      0.42     58402
weighted avg       0.62      0.70      0.58     58402



In [109]:
from sklearn.ensemble import RandomForestClassifier
#class_weight = dict({2:1, 1:15, 0:50})
rdf = RandomForestClassifier(bootstrap=True,
            class_weight="balanced_subsample", 
            criterion='gini',
            max_depth=8, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=4, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=300,
            oob_score=True,
            random_state=35,
            verbose=0, warm_start=False)

In [108]:
rdf.fit(X_train,y_train)

y_pred=rdf.predict(X_test)
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Accuracy: 0.6078387726447725
[[24379 16582]
 [ 6321 11120]]
              precision    recall  f1-score   support

           1       0.79      0.60      0.68     40961
           2       0.40      0.64      0.49     17441

   micro avg       0.61      0.61      0.61     58402
   macro avg       0.60      0.62      0.59     58402
weighted avg       0.68      0.61      0.62     58402



In [110]:
from xgboost import XGBClassifier
model = XGBClassifier(learning_rate =0.07, n_estimators=300,
                      class_weight="balanced_subsample",
                      max_depth=8, min_child_weight=1,
                      scale_pos_weight=7,
                      seed=27,subsample=0.8,colsample_bytree=0.8)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Accuracy: 0.3726755933015993
[[ 4554 36407]
 [  230 17211]]
              precision    recall  f1-score   support

           1       0.95      0.11      0.20     40961
           2       0.32      0.99      0.48     17441

   micro avg       0.37      0.37      0.37     58402
   macro avg       0.64      0.55      0.34     58402
weighted avg       0.76      0.37      0.28     58402



In [112]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test, y_pred))
confusion_matrix(y_test, y_pred)
print(format(classification_report(y_test, y_pred)))

0.6910551008527105
              precision    recall  f1-score   support

           1       0.71      0.96      0.81     40961
           2       0.38      0.06      0.10     17441

   micro avg       0.69      0.69      0.69     58402
   macro avg       0.54      0.51      0.46     58402
weighted avg       0.61      0.69      0.60     58402



In [113]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(loss="deviance", learning_rate=0.1, 
      n_estimators=100, subsample=1.0, criterion="friedman_mse", 
      min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
      max_depth=3, min_impurity_decrease=0.0, min_impurity_split=None, init=None, 
      random_state=None, max_features=None, verbose=0, max_leaf_nodes=None, warm_start=False, 
      presort="auto")

y_pred = gbc.fit(X_train, y_train.values.ravel()).predict(X_test)
print(format(classification_report(y_test, y_pred)))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.70      1.00      0.82     40961
           2       0.45      0.01      0.01     17441

   micro avg       0.70      0.70      0.70     58402
   macro avg       0.58      0.50      0.42     58402
weighted avg       0.63      0.70      0.58     58402

0.7009177767884661
